add mac target, update a few small things

diff --git a/bin/git-del b/bin/git-del
--- a/bin/git-del
+++ b/bin/git-del
@@ -1,38 +1,78 @@
 #!/bin/sh
+
 cur_branch=`git rev-parse --abbrev-ref HEAD`
 cur_commit=`git rev-parse --verify HEAD`
-branch=$cur_branch
 
-# default_ref=$cur_commit
-default_ref=master
+usage () {
+  >&2 cat <<EOF
+Usage: `basename $0` [options] [BRANCH]
 
-dry=0
+BRANCH   The branch to delete. Default is the current branch ($cur_branch)
 
-c=0
+options:
+  -d, --dry-run    Print the operations that would be performed, rather than
+                   actually performing them.
+  -r, --ref <REF>  Specify a ref to checkout after branch deletion if you are
+                   on the branch that will be deleted.  (default: master)
+  -c, --current-commit
+                   Equivalent to --ref $cur_commit
+EOF
+  exit 1
+}
+
+assert_valid_branch() {
+  b="$1"
+  if ! git branch | sed 's_^.\{0,1\}  *__' | grep -q "^$b$"
+  then
+    >&2 echo "invalid branch: $b"
+    usage
+  fi
+}
+
+branch=$cur_branch # what we'll be deleting
+default_ref=master # where we'll end up after
+
+dry_run=0
+c=0 # positional argument counter
 while [ $# -gt 0 ]
 do
   case "$1" in
-    --dry|--dry-run)
-      dry=1
+    -d|--dry|--dry-run)
+      dry_run=1
       shift
+      ;;
+    -c|--current|--current-commit)
+      default_ref="$cur_commit"
+      shift
+      ;;
+    -r|--ref)
+      shift
+      default_ref="$1"
+      shift
+      ;;
+    --help)
+      usage
       ;;
     *)
       c=$((c+1))
       if [ $c -eq 1 ]
       then branch="$1"
-      else >&2 echo "Usage: `basename $0` [--dry-run] [branch]" ; exit 1
+      else usage
       fi
       shift
       ;;
   esac
 done
 
+
+assert_valid_branch "$branch"
+
 tracking=`git rev-parse --symbolic-full-name --abbrev-ref $branch@{u} 2>/dev/null`
 if [ $? -eq 0 ]
 then
   tracking_remote=`echo $tracking | sed 's_/.*$__'`
   tracking_branch=`echo $tracking | sed 's_^[^/]*/__'`
-  if [ $dry -gt 0 ]
+  if [ $dry_run -gt 0 ]
   then echo "git push $tracking_remote --delete $tracking_branch"
   else git push $tracking_remote --delete $tracking_branch
   fi
@@ -40,13 +80,13 @@ fi
 
 if [ "$cur_branch" = "$branch" ]
 then
-  if [ $dry -gt 0 ]
+  if [ $dry_run -gt 0 ]
   then echo "git checkout $default_ref"
   else git checkout $default_ref
   fi
 fi
 
-if [ $dry -gt 0 ]
+if [ $dry_run -gt 0 ]
 then echo "git branch -D $branch"
 else git branch -D $branch
 fi
diff --git a/bin/git-nb b/bin/git-nb
--- a/bin/git-nb
+++ b/bin/git-nb
@@ -1,15 +1,56 @@
 #!/bin/bash
-remote=`git remote | head -n 1` # default remote
-branch=
-dry=0
 
-c=0
+remote=`git config --get core.defaultremote` # default remote
+if [ $? -ne 0 ]
+then remote=`git remote | head -n 1`
+fi
+branch= # new branch name
+
+usage () {
+  >&2 cat <<EOF
+Usage: `basename $0` [options] [REMOTE] BRANCH
+  Make a new branch and set up tracking automatically.
+
+BRANCH   The name of the new branch to be created.
+REMOTE   The remote that the new branch should track on.
+         (default: $remote)
+
+options:
+  -d, --dry-run   Print the operations that would be performed, rather than
+                  actually performing them.
+EOF
+  exit 1
+}
+
+assert_valid_branch() {
+  b="$1"
+  if [ -z "$b" ]
+  then
+    >&2 echo "invalid branch: $b"
+    usage
+  fi
+}
+
+assert_valid_remote() {
+  r="$1"
+  if ! git remote | grep -q "^$r$"
+  then
+    >&2 echo "invalid remote: $r"
+    usage
+  fi
+}
+
+dry_run=0
+c=0 # positional argument counter
 while [ $# -gt 0 ]
 do
   case "$1" in
-    --dry|--dry-run)
-      dry=1
+    -d|--dry|--dry-run)
+      dry_run=1
       shift
+      ;;
+    -h|--help)
+      usage
       ;;
     *)
       c=$((c+1))
@@ -19,21 +60,17 @@ do
       then
         remote="$branch"
         branch="$1"
-      else >&2 echo "Usage: `basename $0` [--dry-run] [remote] branch" ; exit 1
+      else usage
       fi
       shift
       ;;
   esac
 done
 
-if [ -z "$branch" ]
-then >&2 echo "invalid branch name" ; exit 1
-fi
-if [ -z "$remote" ]
-then >&2 echo "invalid remote name" ; exit 1
-fi
+assert_valid_branch "$branch"
+assert_valid_remote "$remote"
 
-if [ $dry -gt 0 ]
+if [ $dry_run -gt 0 ]
 then
   echo "git checkout -b $branch"
   echo "git push -u $remote $branch"
